"""add_trading_oversight_columns

Revision ID: 01a7f6ae4419
Revises: 3a8064b61497
Create Date: 2026-02-25 09:11:51.506511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a7f6ae4419'
down_revision: Union[str, Sequence[str], None] = '3a8064b61497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trading_block_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trading_block_reason')
        batch_op.drop_column('trading_blocked')

    # ### end Alembic commands ###
