"""added_sender_and_receiver_nullable

Revision ID: 6b64421d4745
Revises: 965e3a7c6a40
Create Date: 2026-02-18 21:40:51.001310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b64421d4745'
down_revision: Union[str, Sequence[str], None] = '965e3a7c6a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_no', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('receiver_no', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('receiver_no')
        batch_op.drop_column('sender_no')

    # ### end Alembic commands ###
