"""upgrade_transaction_model_for_external_transfers

Revision ID: 965e3a7c6a40
Revises: cd8b00e9c0e6
Create Date: 2026-02-18 21:15:08.607458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965e3a7c6a40'
down_revision: Union[str, Sequence[str], None] = 'cd8b00e9c0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_swift_bic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_iban_or_acc', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recipient_full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recipient_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('purpose_of_transfer', sa.String(), nullable=True))
        batch_op.alter_column('receiver_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
        batch_op.alter_column('fee',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('fee',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('receiver_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('purpose_of_transfer')
        batch_op.drop_column('recipient_address')
        batch_op.drop_column('recipient_full_name')
        batch_op.drop_column('external_iban_or_acc')
        batch_op.drop_column('external_swift_bic')
        batch_op.drop_column('external_bank_name')
        batch_op.drop_column('transfer_type')

    # ### end Alembic commands ###
